<a href="https://colab.research.google.com/github/chiou99/-/blob/master/opkkk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import tensorflow as tf
print(tf.__version__)
x=tf.random.normal([2,784])
w1=tf.Variable(tf.random.truncated_normal([784,256],stddev=0.1))
b1=tf.Variable(tf.zeros([256]))
o1=tf.matmul(x,w1)+b1
o1=tf.nn.relu(o1)
o1

2.3.0


<tf.Tensor: shape=(2, 256), dtype=float32, numpy=
array([[1.1441405e+00, 8.8986039e-01, 3.3379529e+00, 0.0000000e+00,
        0.0000000e+00, 2.6837094e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.2588382e-01, 0.0000000e+00, 1.4885905e+00,
        0.0000000e+00, 0.0000000e+00, 1.9507658e+00, 1.1492219e+00,
        5.7103312e-01, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        3.1691833e+00, 2.3795090e+00, 2.7361941e-01, 0.0000000e+00,
        2.9125805e+00, 0.0000000e+00, 0.0000000e+00, 1.4879589e+00,
        0.0000000e+00, 5.5391407e+00, 0.0000000e+00, 3.3816533e+00,
        1.4498049e-01, 2.0366883e-01, 0.0000000e+00, 0.0000000e+00,
        3.0379736e-01, 5.9331455e+00, 4.1038208e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 3.0278168e+00, 1.4183457e+00,
        6.0270315e-01, 0.0000000e+00, 1.8611553e+00, 2.2521639e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 2.9539871e+00,
        3.0559530e+00, 2.5075598e+00, 1.3888384e+00, 1.2940404e+00

In [14]:
x=tf.random.normal([4,28*28])
from tensorflow.keras import layers
fc=layers.Dense(512,activation=tf.nn.relu)
h1=fc(x)
fc.kernel
fc.bias

<tf.Variable 'dense_3/bias:0' shape=(512,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 

In [24]:

f1=layers.Dense(512,activation=tf.nn.relu)
f2=layers.Dense(256,activation=tf.nn.relu)
f3=layers.Dense(128,activation=tf.nn.relu)
f4=layers.Dense(64,activation=tf.nn.relu)
f5=layers.Dense(32,activation=tf.nn.relu)
f6=layers.Dense(16,activation=tf.nn.relu)
f7=layers.Dense(10,activation=tf.nn.relu)
h1=f1(x)
h2=f2(h1)
h3=f3(h2)
h4=f4(h3)
h5=f5(h4)
h6=f6(h5)
h7=f7(h6)
f7.kernel
f6.kernel

<tf.Variable 'dense_17/kernel:0' shape=(32, 16) dtype=float32, numpy=
array([[-0.29335463,  0.31902733,  0.29597357,  0.21171102, -0.04604736,
         0.16198781,  0.18271592,  0.09037632,  0.1714609 ,  0.26266345,
         0.19131759,  0.21841803, -0.24462031,  0.11861092,  0.226675  ,
        -0.11479369],
       [ 0.0332306 ,  0.18005916,  0.15855423, -0.09233212, -0.30892855,
         0.07812324, -0.3072346 , -0.03962791,  0.33312723,  0.13494688,
        -0.04302391, -0.05255342,  0.02513689, -0.2146281 , -0.04475337,
         0.33577767],
       [-0.23248824,  0.18080106,  0.20536414, -0.27240983, -0.20882179,
         0.2756072 , -0.29288232,  0.02687603,  0.2353485 , -0.25414127,
         0.17304501, -0.17182916, -0.00787091,  0.23929688,  0.06067798,
        -0.29318425],
       [ 0.26425508, -0.22101487, -0.25947598,  0.03285801, -0.19907346,
         0.02127767, -0.0430229 ,  0.13946772, -0.11270422,  0.11382666,
         0.10360244,  0.04206491, -0.33640274,  0.35303167, -