<a href="https://colab.research.google.com/github/chiou99/-/blob/master/test3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
a=np.array([1,2,3])
print(a.shape)
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)

(3,)
(2, 3)


In [48]:
a=np.array(
    [
     [
      [1,2],
      [3,4],
      [5,6]
     ],
     [
      [7,8],
      [9,10],
      [11,12]
     ]
    ]
)#2x3x2
print(a[0:1][0:3][0:1])

[[[1 2]
  [3 4]
  [5 6]]]


In [52]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x.shape
y=np.reshape(x,(1,9,1))
y


array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]])

In [66]:
x=np.zeros( (3,5,2) )
x.ndim, x.shape,  x.dtype
x=np.zeros(5)
y=x.astype('uint8')
x,  x.shape,  y.dtype
x=np.ones((2,3))
x
x=np.full((2,3),7)
xx=np.arange(5)
x=np.full((2,3),7)
y=np.zeros_like(y)
z=np.ones_like(y)
z=np.shape
z=np.reshape(z,(1,2,3))
z
q=np.transpose(z)
q

ValueError: ignored

In [63]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a+b
c
a=np.array([[1],[2]])
b=np.array([3,4])
a.shape,b.shape
c=a+b
c

array([[4, 5],
       [5, 6]])

In [72]:
a=np.array([[85,90,77],[88,82,93]])
a
np.max(a,axis=0)
np.max(a,axis=1)
np.max(a)
a.shape
np.mean(a,axis=0)

array([86.5, 86. , 85. ])

(2,3)2個1維陣列(有3個元素)
(2,2,3) 2個2x3個陣列